name: 'Python Package New Version'
description: 'Automatically checks pyproject.toml and Pypi.org to know if this package needs a new version'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
      - ${{ inputs.path }}

inputs:
  path:
    description: 'Path to pyproject.toml'
    required: false
    default: 'pyproject.toml'

branding:
  color: "yellow"
  icon: "package"
