name: Test, build and publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository containing the action
      - name: Checkout Action Repository
        uses: actions/checkout@v3
        with:
          repository: MathieuMoalic/action-python-package-new-version
          path: 'action-repo'  # Saves the repo in a folder named 'action-repo'

      # Checkout the repository you want to operate on
      - name: Checkout Python Package Repository
        uses: actions/checkout@v3
        with:
          repository: MathieuMoalic/pyzfn

      # Use the local action
      - name: Python Package New Version
        uses: ./action-repo